CREATE SCHEMA produktiv;

CREATE TABLE produktiv.users(
id UUID PRIMARY KEY,
username VARCHAR(30) UNIQUE,
password_hash TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE produktiv.tasks (
id SERIAL PRIMARY KEY,
user_id UUID NOT NULL REFERENCES produktiv.users(id) ON DELETE CASCADE,
title VARCHAR(50),
description VARCHAR(500),
priority INTEGER,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
